chore: FIXME runtime failure for python pure build
Error message:
```
ModuleNotFoundError: No module named 'quotes_app_python'
```

I also had to modify the `hook.on-activate` script so that it wouldn't
generate error messages at runtime. `FLOX_ENV_CACHE` isn't populated in
builds, so Poetry was attempting to create virtual environments under
`/poetry/virtualenvs`.