fix(nodejs): Use cp -R instead of -r
This project failed to build when run from a shell that didn't have `cp`
from `coreutils` from the system or a nested activation because the deps
build copied the target of symlinks instead of the symlinks themselves.

This only surfaced to half of the CLI team and in CI when introducing
matrix builds for macOS.

In the future we will provide `coreutils` for non-sandboxed builds to
reduce these kinds of surprises (flox/flox#3340) but in the meantime we
can use the `-R` instead of the discouraged `-r` flag:

> Historic versions of the cp utility had a -r option.  This
> implementation supports that option, however, its behavior is
> different from historical FreeBSD behavior.
>
> Use of this option is strongly discouraged as the behavior is
> implementation-dependent.  In FreeBSD, -r is a synonym for -RL and
> works the same unless modified by other flags.
>
> Historical implementations of -r differ as they copy special files as
> normal files while recreating a hierarchy.

I've updated all occurrences in this environment. There are no other
occurrences of the lowercase flag in other environments in this repo.

Original error:

    quotes-app-nodejs-pure> 00:00:00.103380 + npm run build
    quotes-app-nodejs-pure> 00:00:00.497438
    quotes-app-nodejs-pure> 00:00:00.497438 > quotes-app@1.0.0 build
    quotes-app-nodejs-pure> 00:00:00.497438 > node ./node_modules/.bin/rollup -c
    quotes-app-nodejs-pure> 00:00:00.497438
    quotes-app-nodejs-pure> 00:00:00.561549 node:internal/modules/cjs/loader:1228
    quotes-app-nodejs-pure> 00:00:00.561549   throw err;
    quotes-app-nodejs-pure> 00:00:00.561549   ^
    quotes-app-nodejs-pure> 00:00:00.561549
    quotes-app-nodejs-pure> 00:00:00.561549 Error: Cannot find module '../shared/rollup.js'
    quotes-app-nodejs-pure> 00:00:00.561549 Require stack:
    quotes-app-nodejs-pure> 00:00:00.561549 - /private/tmp/nix-build-quotes-app-nodejs-pure-0.0.1.drv-0/quotes-app-nodejs-pure-0.0.1/node_modules/.bin/rollup
    quotes-app-nodejs-pure> 00:00:00.561549     at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    quotes-app-nodejs-pure> 00:00:00.561549     at Function._load (node:internal/modules/cjs/loader:1055:27)
    quotes-app-nodejs-pure> 00:00:00.561549     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    quotes-app-nodejs-pure> 00:00:00.561549     at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    quotes-app-nodejs-pure> 00:00:00.561549     at Module.require (node:internal/modules/cjs/loader:1311:12)
    quotes-app-nodejs-pure> 00:00:00.561549     at require (node:internal/modules/helpers:136:16)
    quotes-app-nodejs-pure> 00:00:00.561549     at Module.<anonymous> (/private/tmp/nix-build-quotes-app-nodejs-pure-0.0.1.drv-0/quotes-app-nodejs-pure-0.0.1/node_modules/.bin/rollup:16:16)
    quotes-app-nodejs-pure> 00:00:00.561549     at Module._compile (node:internal/modules/cjs/loader:1554:14)
    quotes-app-nodejs-pure> 00:00:00.561549     at Object..js (node:internal/modules/cjs/loader:1706:10)
    quotes-app-nodejs-pure> 00:00:00.561549     at Module.load (node:internal/modules/cjs/loader:1289:32) {
    quotes-app-nodejs-pure> 00:00:00.561549   code: 'MODULE_NOT_FOUND',
    quotes-app-nodejs-pure> 00:00:00.561549   requireStack: [
    quotes-app-nodejs-pure> 00:00:00.561549     '/private/tmp/nix-build-quotes-app-nodejs-pure-0.0.1.drv-0/quotes-app-nodejs-pure-0.0.1/node_modules/.bin/rollup'
    quotes-app-nodejs-pure> 00:00:00.561549   ]
    quotes-app-nodejs-pure> 00:00:00.561549 }
    quotes-app-nodejs-pure> 00:00:00.561549
    quotes-app-nodejs-pure> 00:00:00.561549 Node.js v22.14.0
    quotes-app-nodejs-pure> flox build failed (caching build dir)
    quotes-app-nodejs-pure> ⚠️  WARNING: No executables found in '$out/bin'.
    quotes-app-nodejs-pure> Only executables in '$out/bin' will be available on the PATH.
    quotes-app-nodejs-pure> If your build produces executables, make sure they are copied to '$out/bin'.
    quotes-app-nodejs-pure>   - copy a single file with 'mkdir -p $out/bin && cp file $out/bin'
    quotes-app-nodejs-pure>   - copy a bin directory with 'mkdir $out && cp -r bin $out'
    quotes-app-nodejs-pure>   - copy multiple files with 'mkdir -p $out/bin && cp bin/* $out/bin'
    quotes-app-nodejs-pure>   - copy files from an Autotools project with 'make install PREFIX=$out'
    ERROR: flox build failed (see result-quotes-app-nodejs-pure-log)
    make[1]: *** [/nix/store/7m1fphfyx1jqpq5pk20d8bhg5d9piy2d-package-builder-1.0.0/libexec/flox-build.mk:716: quotes_app_nodejs_pure_CHECK_BUILD] Error 1
    ❌ ERROR: Build failed with status: exit status: 2